#!/usr/bin/env bash

#Team Orange Server
#MPL-2.0

if [[ -e /usr/bin/x-terminal-emulator ]]; then
    /usr/bin/x-terminal-emulator -e "watch -n1 "nvidia-smi""
else
    /usr/bin/konsole -e "watch -n1 "nvidia-smi""
fi
